### ISSUE TITLE
Borderlands 2 crashes on Ubuntu

### ISSUE THREAD

**Issue by whitem0nkey** [bl-sdk/PythonSDK#101]
Using Proton-7.1-GE-2, with launch option: "WINEDLLOVERRIDES="ddraw=n,b" bash -c 'exec "${@/Launcher.exe/Borderlands2.exe}"' -- %command%". 

OS: Ubuntu 20.04.4 LTS

The game crashes when I open Borderlands 2 with the launch options mentioned.

**Comment by apple1417** [comment]
For support join the [Borderlands Modding Support Discord](https://discord.gg/bXeqV8Ef9R).
