### ISSUE TITLE
Filesystem Rework

### ISSUE THREAD

**Issue by mopioid** [bl-sdk/PythonSDK#31]
Currently the SDK requires the user to navigate a complex - and therefore error prone - assortment of files and folders for both installation and usage.
```
ddraw.dll
Plugins\
Plugins\python36.dll
Plugins\python36.zip
Plugins\pythonSDK.dll
Plugins\Python\
Plugins\Python\[mod].py
```
With even more complexity necessary to use mods that depend on additional files as resources:
```
Plugins\Python\[mod's library dependency].py
Plugins\Python\Textures\
Plugins\Python\Textures\[Texture file imported by mod].png
```
...etcetera.

A new approach is proposed in order to both simplify this for the user and allow developers freedom in bundling resources with their mods:
```
ddraw.dll
Mods\
Mods\[mod]\
Mods\[mod]\[mod resource]
```
In this proposed structure, `ddraw.dll` includes the libraries and resources the SDK itself is dependent on. (It may possibly also perform loading of additional DLLs located in `Plugins\`, if the user has any, to retain compatibility with existing plugins).

Besides installation of the SDK itself, this would also simply installation of mods, as the user would only be responsible for copying a single directory for each mod.

**Comment by Matt-Hurd** [comment]
Hugely agree with this. I'm not sure if it will be possible to build all of the dependencies into `ddraw.dll`, but copying the PluginLoader should be simple, as that code is already (somewhere) in this repo's history.

**Comment by mopioid** [comment]
Great!

I believe it would be *possible* to build even `python36.zip` into the main DLL (as a byte array if nothing else), but if actually using it in this fashion is non-trivial, then it’s not too much to ask the user to copy a couple extra files when installing the SDK.
