### ISSUE TITLE
Cyrillic support

### ISSUE THREAD

**Issue by vanja-san** [bl-sdk/PythonSDK#76]
Please add Russian language support! And then in the settings for the assignment of keys, incomprehensible characters.
<details>
  <summary>Screenshot</summary>
  
  ![изображение](https://user-images.githubusercontent.com/7201687/93903363-bffd8600-fd22-11ea-8c1a-308c593c99e6.png)
  
</details>

**Comment by apple1417** [comment]
Like that commit message hints at, should be fixed in an upcoming release, for now you can try replace your `ddraw.dll` with this one.

[ddraw.zip](https://github.com/bl-sdk/PythonSDK/files/5923051/ddraw.zip)
