### ISSUE TITLE
Language&Encoding Problem

### ISSUE THREAD

**Issue by BecksIsAlreadyTaken** [bl-sdk/PythonSDK#79]
Hi, i am a player who use Simplified Chinese Language 
There is a problem when adding pythonSDK to borderlands 2

[Main Menu](https://github.com/BecksIsAlreadyTaken/Troubleshooting/blob/main/mainmenu.png)
[Mod Control Settings](https://github.com/BecksIsAlreadyTaken/Troubleshooting/blob/main/ModdedControlSettings.png)
[Keyboard Control Settings](https://github.com/BecksIsAlreadyTaken/Troubleshooting/blob/main/KeyboardControlSettings.png)

**Comment by apple1417** [comment]
Duplicate of #76
