### ISSUE TITLE
Add extra fields to save files

### ISSUE THREAD

**Issue by Matt-Hurd** [bl-sdk/PythonSDK#8]
Mods will be adding new items, weapons, etc, and these are not currently persisted throughout saves. For these mods to be viable, we'll need to modify save files a bit.

My current proposal is to add a field that is only accessible in C++, that can make saves dependent on certain mods. Skyrim has some system whereby saves know which mods they were made with, and notifies the user that the save may not function properly without them.

This would need to be shown on the main menu when hovering over "Continue" and in the "Select Character" menu when hovering over a file.

**Comment by mopioid** [comment]
This is a very obvious issue that I totally did not consider.

Haven’t looked into the save file design, my assumption was each weapon was simply an assortment of strings, which then looked up the corresponding part objects by name?

**Comment by apple1417** [comment]
Superseded by bl-sdk/bl2-mod-manager#1
