### ISSUE TITLE
ddraw.dll seems to cause immediate crashes

### ISSUE THREAD

**Issue by snoozysoft** [bl-sdk/PythonSDK#89]
Hi there. Been trying to play around with some BL2 mods to spice it up a bit more. Trying to achieve something simple before going in on other mods: use apple1417's [SDK Autorun mod](https://github.com/apple1417/bl-sdk-mods/wiki/SDK-Autorun) to load up UCP on launch. But I'm hitting the snag as described in the title. If ddraw.dll is there, the game briefly shows the splash screen before crashing completely. If it's not there, the game loads up perfectly fine with no issues. I've followed and checked all the various (now kind of outdated) guides and I've done everything right as far as I can see. The issue is purely down to ddraw. I figured maybe the Valorant anti-cheat thing might be preventing it, so I closed that, and nope it still crashes.

Sitting next to the python files in the Binaries/Win32 folder is this log file, which reads thus:

======= Borderlands 2 Python Loader =======
[AntiDebug] Hook added for NtSetInformationThread
[AntiDebug] Hook added for NtQueryInformationProcess
Found EXE name as 'Borderlands2.exe'
[Internal] GObjects = 0x019CAB20
[Internal] GNames = 0x01988744
[Internal] UObject::ProcessEvent() = 0x004F27F0
[Internal] UObject::CallFunction() = 0x004F2300
[Internal] FFrame::Step() = 0x004E31B0
[Internal] UObject::StaticConstructObject() = 0x00429D20
[Internal] UObject::LoadPackage() = 0x0042C8C0
[Internal] GMalloc = 0x0193A8F4
[Internal] FindOrCreateFName = 0x003F08D0
[Internal] GetDefaultObject = 0x003C1F20
Sigscan failed (Signature not found, Mask = FF 83 C4 0C 85 C0 75 1A 6A 01 8D)WINAPI Error when enabling 'SET' commands: 487
Plugin loaded: d
[AntiDebug] NtSetInformationThread called with ThreadHideFromDebugger

I've searched up and down for some kind of fix or alternative solution to this problem and the most I found was just [another random mod](https://www.nexusmods.com/borderlands2/mods/81?tab=description) that acknowledges ddraw.dll can prevent the game from starting up. Any ideas?

**Comment by juso40** [comment]
Your crash is most likely because of a ``say`` command in the UCP. While offline ``say`` commands will crash your game. So this issue is kinda related to SDK Autorun, and not because of the SDK.

**Comment by snoozysoft** [comment]
...Okay yeah, go figure it was the _one_ goddamn thing I didn't think to check. It's loading fine now, many thanks, haha.

**Comment by xXDark47Xx** [comment]
I have the same problem and I'm new to modding
so I don't know how to fix this problem.
Help me please

**Comment by juso40** [comment]
Might post the content of ``Steam\steamapps\common\Borderlands 2\Binaries\Win32\python-sdk.log`` here, that would help troubleshooting.

**Comment by xXDark47Xx** [comment]
======= Borderlands 2 Python Loader =======
[AntiDebug] Hook added for NtSetInformationThread
[AntiDebug] Hook added for NtQueryInformationProcess
Found EXE name as 'Borderlands2.exe'
[Internal] GObjects = 0x0226F920
[Internal] GNames = 0x0222D544
[Internal] UObject::ProcessEvent() = 0x00DA15E0
[Internal] UObject::CallFunction() = 0x00DA10F0
[Internal] FFrame::Step() = 0x00D91D30
[Internal] UObject::StaticConstructObject() = 0x00CD8DB0
[Internal] UObject::LoadPackage() = 0x00CDB950
[Internal] GMalloc = 0x021DF6F0
[Internal] FindOrCreateFName = 0x00CA1140
[Internal] GetDefaultObject = 0x00C723D0
Sigscan failed (Signature not found, Mask = 83 C4 0C 85 C0 75 1A 6A 01 8D)[Internal] SetCommand = 0x00000000
WINAPI Error when enabling 'SET' commands: 487
Plugin loaded: d

This ?
